version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    networks:
      - app-network
    environment:
      - ENABLE_CORS=true

  frontend:
    build:
      context: ./frontend
    ports:
      - "5501:8080" # Map container port 8080 to host port 5501
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
