services:
  - type: web
    name: frontend-service
    env: docker
    plan: free
    repo: https://github.com/GabrielMalone/latin
    branch: main
    dockerfilePath: frontend/Dockerfile
    buildCommand: |
      ls -al
      ls -al frontend
      docker build -t frontend -f frontend/Dockerfile .
    startCommand: docker run -p 8080:8080 frontend

  - type: web
    name: backend-service
    env: docker
    plan: free
    repo: https://github.com/GabrielMalone/latin
    branch: main
    dockerfilePath: backend/Dockerfile
    buildCommand: |
      ls -al
      ls -al backend
      docker build -t backend -f backend/Dockerfile .
    startCommand: docker run -p 8000:8000 backend
